PACKAGE_NAME="mt7902e-wifi"
PACKAGE_VERSION="1.0"

BUILT_MODULE_NAME[0]="mt7902e"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/mt7902e-wifi"

MAKE[0]="make KVER=${kernelver} KERNELRELEASE=${kernelver} -j$(nproc)"
CLEAN="make clean"

AUTOINSTALL="yes"
